INSERT INTO USER (ID, NAME, VIP) VALUES ('1', 'John', true);

INSERT INTO PRODUCT(ID, NAME, PRICE) VALUES ('1', 'Shoes', 150);
INSERT INTO PRODUCT(ID, NAME, PRICE) VALUES ('2', 'Dress', 500);
INSERT INTO PRODUCT(ID, NAME, PRICE) VALUES ('3', 'Tshirt', 75);
INSERT INTO PRODUCT(ID, NAME, PRICE) VALUES ('4', 'Gloves', 300);