CREATE TABLE USER (
  ID VARCHAR PRIMARY KEY,
  NAME VARCHAR,
  VIP BOOLEAN
);

CREATE TABLE PRODUCT (
  ID VARCHAR PRIMARY KEY,
  NAME VARCHAR,
  PRICE NUMERIC
);

CREATE TABLE ORDER_POSITION (
  ID VARCHAR PRIMARY KEY,
  ORDER_ID VARCHAR,
  PRODUCT_ID VARCHAR,
  QUANTITY NUMERIC
);

CREATE TABLE ORDER_DATA (
  ID VARCHAR PRIMARY KEY,
  OWNER_ID VARCHAR,
  STATUS VARCHAR,
  CONFIRMED_TOTAL_PRICE NUMERIC
);



