create TABLE USER (
  ID VARCHAR PRIMARY KEY,
  NAME VARCHAR,
  VIP BOOLEAN
);

create TABLE PRODUCT (
  ID VARCHAR PRIMARY KEY,
  NAME VARCHAR,
  PRICE NUMERIC
);

create TABLE DRAFT_ORDER (
  ID VARCHAR PRIMARY KEY,
  CORRELATED_ORDER_ID VARCHAR,
  OWNER_ID VARCHAR
);

create TABLE ACCEPTED_ORDER (
  ID VARCHAR PRIMARY KEY,
  CORRELATED_ORDER_ID VARCHAR,
  OWNER_ID VARCHAR
);

create TABLE VIP_ORDER (
  ID VARCHAR PRIMARY KEY,
  CORRELATED_ORDER_ID VARCHAR,
  OWNER_ID VARCHAR
);

create TABLE CONFIRMED_ORDER (
  ID VARCHAR PRIMARY KEY,
  CORRELATED_ORDER_ID VARCHAR,
  OWNER_ID VARCHAR,
  CONFIRMED_TOTAL_PRICE NUMERIC
);

create TABLE ORDER_POSITION (
  ORDER_ID VARCHAR,
  PRODUCT_ID VARCHAR,
  QUANTITY NUMERIC
);

create TABLE ORDER_PROCESS (
  ID VARCHAR PRIMARY KEY,
  STEP_ID VARCHAR,
  STATUS VARCHAR,
  CORRELATED_ORDER_ID VARCHAR,
  STEP NUMERIC
);


